name: Execute CircleCI Workflow

on:
  workflow_dispatch:
    inputs:
      build_env:
        description: 'Build Environment'
        required: true
        default: 'UA001' 
        type: choice
        options:
        - UA001
        - UA002
        - PACKG 

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Capture triggering branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Trigger CircleCI build-beta workflow.
        uses: promiseofcake/circleci-trigger-action@v1
        with:
          user-token: ${{ secrets.CIRCLECI_TOKEN }}
          project-slug: bang9/gh-to-circleci
          branch: ${{ env.BRANCH_NAME }}
          payload: '{"build_env": "${{ github.event.inputs.build_env }}" }'
